/*
 * Form1.Designer.cs
 * generated by form designer
 */
namespace RetailStoreApp
{
    partial class RetailStore
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.customerListbox = new System.Windows.Forms.ListBox();
            this.nameText = new System.Windows.Forms.TextBox();
            this.addressText = new System.Windows.Forms.TextBox();
            this.phonenumText = new System.Windows.Forms.TextBox();
            this.idText = new System.Windows.Forms.TextBox();
            this.mailingCheckbox = new System.Windows.Forms.CheckBox();
            this.searchText = new System.Windows.Forms.TextBox();
            this.searchbyCbox = new System.Windows.Forms.ComboBox();
            this.amountText = new System.Windows.Forms.TextBox();
            this.levelText = new System.Windows.Forms.TextBox();
            this.nameLabel = new System.Windows.Forms.Label();
            this.addressLabel = new System.Windows.Forms.Label();
            this.phonenumLabel = new System.Windows.Forms.Label();
            this.idLabel = new System.Windows.Forms.Label();
            this.mailingLabel = new System.Windows.Forms.Label();
            this.amountLabel = new System.Windows.Forms.Label();
            this.levelLabel = new System.Windows.Forms.Label();
            this.newBtn = new System.Windows.Forms.Button();
            this.updateBtn = new System.Windows.Forms.Button();
            this.deleteBtn = new System.Windows.Forms.Button();
            this.loadBtn = new System.Windows.Forms.Button();
            this.modeLabel = new System.Windows.Forms.Label();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.purchaseText = new System.Windows.Forms.TextBox();
            this.discText = new System.Windows.Forms.TextBox();
            this.calcBtn = new System.Windows.Forms.Button();
            this.groupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // customerListbox
            // 
            this.customerListbox.FormattingEnabled = true;
            this.customerListbox.Location = new System.Drawing.Point(23, 70);
            this.customerListbox.Name = "customerListbox";
            this.customerListbox.Size = new System.Drawing.Size(356, 160);
            this.customerListbox.TabIndex = 0;
            this.customerListbox.SelectedIndexChanged += new System.EventHandler(this.customerListbox_SelectedIndexChanged);
            // 
            // nameText
            // 
            this.nameText.Location = new System.Drawing.Point(140, 282);
            this.nameText.Name = "nameText";
            this.nameText.Size = new System.Drawing.Size(239, 20);
            this.nameText.TabIndex = 1;
            // 
            // addressText
            // 
            this.addressText.Location = new System.Drawing.Point(140, 308);
            this.addressText.Name = "addressText";
            this.addressText.Size = new System.Drawing.Size(239, 20);
            this.addressText.TabIndex = 2;
            // 
            // phonenumText
            // 
            this.phonenumText.Location = new System.Drawing.Point(140, 334);
            this.phonenumText.Name = "phonenumText";
            this.phonenumText.Size = new System.Drawing.Size(239, 20);
            this.phonenumText.TabIndex = 3;
            // 
            // idText
            // 
            this.idText.Enabled = false;
            this.idText.Location = new System.Drawing.Point(140, 379);
            this.idText.Name = "idText";
            this.idText.Size = new System.Drawing.Size(239, 20);
            this.idText.TabIndex = 4;
            // 
            // mailingCheckbox
            // 
            this.mailingCheckbox.AutoSize = true;
            this.mailingCheckbox.Location = new System.Drawing.Point(140, 405);
            this.mailingCheckbox.Name = "mailingCheckbox";
            this.mailingCheckbox.Size = new System.Drawing.Size(72, 17);
            this.mailingCheckbox.TabIndex = 5;
            this.mailingCheckbox.Text = "subcribed";
            this.mailingCheckbox.UseVisualStyleBackColor = true;
            // 
            // searchText
            // 
            this.searchText.Location = new System.Drawing.Point(150, 33);
            this.searchText.Name = "searchText";
            this.searchText.Size = new System.Drawing.Size(229, 20);
            this.searchText.TabIndex = 6;
            this.searchText.TextChanged += new System.EventHandler(this.searchText_TextChanged);
            // 
            // searchbyCbox
            // 
            this.searchbyCbox.Cursor = System.Windows.Forms.Cursors.Arrow;
            this.searchbyCbox.FormattingEnabled = true;
            this.searchbyCbox.Items.AddRange(new object[] {
            "ID",
            "Name"});
            this.searchbyCbox.Location = new System.Drawing.Point(23, 33);
            this.searchbyCbox.Name = "searchbyCbox";
            this.searchbyCbox.Size = new System.Drawing.Size(121, 21);
            this.searchbyCbox.TabIndex = 7;
            this.searchbyCbox.Text = "ID";
            this.searchbyCbox.SelectedIndexChanged += new System.EventHandler(this.searchbyCbox_SelectedIndexChanged);
            // 
            // amountText
            // 
            this.amountText.Location = new System.Drawing.Point(140, 444);
            this.amountText.Name = "amountText";
            this.amountText.Size = new System.Drawing.Size(239, 20);
            this.amountText.TabIndex = 8;
            // 
            // levelText
            // 
            this.levelText.Location = new System.Drawing.Point(140, 471);
            this.levelText.Name = "levelText";
            this.levelText.Size = new System.Drawing.Size(239, 20);
            this.levelText.TabIndex = 9;
            // 
            // nameLabel
            // 
            this.nameLabel.AutoSize = true;
            this.nameLabel.Location = new System.Drawing.Point(32, 285);
            this.nameLabel.Name = "nameLabel";
            this.nameLabel.Size = new System.Drawing.Size(35, 13);
            this.nameLabel.TabIndex = 10;
            this.nameLabel.Text = "Name";
            // 
            // addressLabel
            // 
            this.addressLabel.AutoSize = true;
            this.addressLabel.Location = new System.Drawing.Point(32, 311);
            this.addressLabel.Name = "addressLabel";
            this.addressLabel.Size = new System.Drawing.Size(45, 13);
            this.addressLabel.TabIndex = 11;
            this.addressLabel.Text = "Address";
            // 
            // phonenumLabel
            // 
            this.phonenumLabel.AutoSize = true;
            this.phonenumLabel.Location = new System.Drawing.Point(32, 337);
            this.phonenumLabel.Name = "phonenumLabel";
            this.phonenumLabel.Size = new System.Drawing.Size(78, 13);
            this.phonenumLabel.TabIndex = 12;
            this.phonenumLabel.Text = "Phone Number";
            // 
            // idLabel
            // 
            this.idLabel.AutoSize = true;
            this.idLabel.Location = new System.Drawing.Point(35, 379);
            this.idLabel.Name = "idLabel";
            this.idLabel.Size = new System.Drawing.Size(91, 13);
            this.idLabel.TabIndex = 13;
            this.idLabel.Text = "Customer Number";
            // 
            // mailingLabel
            // 
            this.mailingLabel.AutoSize = true;
            this.mailingLabel.Location = new System.Drawing.Point(35, 406);
            this.mailingLabel.Name = "mailingLabel";
            this.mailingLabel.Size = new System.Drawing.Size(90, 13);
            this.mailingLabel.TabIndex = 15;
            this.mailingLabel.Text = "Promotion Mailing";
            // 
            // amountLabel
            // 
            this.amountLabel.AutoSize = true;
            this.amountLabel.Location = new System.Drawing.Point(35, 447);
            this.amountLabel.Name = "amountLabel";
            this.amountLabel.Size = new System.Drawing.Size(103, 13);
            this.amountLabel.TabIndex = 16;
            this.amountLabel.Text = "Amount of Purchase";
            // 
            // levelLabel
            // 
            this.levelLabel.AutoSize = true;
            this.levelLabel.Location = new System.Drawing.Point(35, 474);
            this.levelLabel.Name = "levelLabel";
            this.levelLabel.Size = new System.Drawing.Size(80, 13);
            this.levelLabel.TabIndex = 17;
            this.levelLabel.Text = "Customer Level";
            // 
            // newBtn
            // 
            this.newBtn.Location = new System.Drawing.Point(40, 244);
            this.newBtn.Name = "newBtn";
            this.newBtn.Size = new System.Drawing.Size(75, 23);
            this.newBtn.TabIndex = 18;
            this.newBtn.Text = "New";
            this.newBtn.UseVisualStyleBackColor = true;
            this.newBtn.Click += new System.EventHandler(this.newBtn_Click);
            // 
            // updateBtn
            // 
            this.updateBtn.Location = new System.Drawing.Point(121, 244);
            this.updateBtn.Name = "updateBtn";
            this.updateBtn.Size = new System.Drawing.Size(75, 23);
            this.updateBtn.TabIndex = 19;
            this.updateBtn.Text = "Update";
            this.updateBtn.UseVisualStyleBackColor = true;
            this.updateBtn.Click += new System.EventHandler(this.updateBtn_Click);
            // 
            // deleteBtn
            // 
            this.deleteBtn.Location = new System.Drawing.Point(202, 244);
            this.deleteBtn.Name = "deleteBtn";
            this.deleteBtn.Size = new System.Drawing.Size(75, 23);
            this.deleteBtn.TabIndex = 20;
            this.deleteBtn.Text = "Delete";
            this.deleteBtn.UseVisualStyleBackColor = true;
            this.deleteBtn.Click += new System.EventHandler(this.deleteBtn_Click);
            // 
            // loadBtn
            // 
            this.loadBtn.Location = new System.Drawing.Point(283, 244);
            this.loadBtn.Name = "loadBtn";
            this.loadBtn.Size = new System.Drawing.Size(75, 23);
            this.loadBtn.TabIndex = 21;
            this.loadBtn.Text = "Load All";
            this.loadBtn.UseVisualStyleBackColor = true;
            this.loadBtn.Click += new System.EventHandler(this.loadBtn_Click);
            // 
            // modeLabel
            // 
            this.modeLabel.AutoSize = true;
            this.modeLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.modeLabel.ForeColor = System.Drawing.Color.Green;
            this.modeLabel.Location = new System.Drawing.Point(25, 9);
            this.modeLabel.Name = "modeLabel";
            this.modeLabel.Size = new System.Drawing.Size(90, 13);
            this.modeLabel.TabIndex = 22;
            this.modeLabel.Text = "Mode : Search";
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.calcBtn);
            this.groupBox1.Controls.Add(this.discText);
            this.groupBox1.Controls.Add(this.purchaseText);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox1.Location = new System.Drawing.Point(35, 511);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(344, 115);
            this.groupBox1.TabIndex = 24;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Discount Estimation";
            this.groupBox1.Enter += new System.EventHandler(this.groupBox1_Enter);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(37, 27);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(90, 13);
            this.label1.TabIndex = 0;
            this.label1.Text = "Purchase amount";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(37, 54);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(87, 13);
            this.label2.TabIndex = 1;
            this.label2.Text = "Discounted price";
            this.label2.Click += new System.EventHandler(this.label2_Click);
            // 
            // purchaseText
            // 
            this.purchaseText.Location = new System.Drawing.Point(154, 24);
            this.purchaseText.Name = "purchaseText";
            this.purchaseText.Size = new System.Drawing.Size(169, 20);
            this.purchaseText.TabIndex = 2;
            // 
            // discText
            // 
            this.discText.Enabled = false;
            this.discText.Location = new System.Drawing.Point(154, 51);
            this.discText.Name = "discText";
            this.discText.Size = new System.Drawing.Size(169, 20);
            this.discText.TabIndex = 3;
            // 
            // calcBtn
            // 
            this.calcBtn.Location = new System.Drawing.Point(134, 86);
            this.calcBtn.Name = "calcBtn";
            this.calcBtn.Size = new System.Drawing.Size(75, 23);
            this.calcBtn.TabIndex = 4;
            this.calcBtn.Text = "Calculate";
            this.calcBtn.UseVisualStyleBackColor = true;
            this.calcBtn.Click += new System.EventHandler(this.calcBtn_Click);
            // 
            // RetailStore
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(409, 638);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.modeLabel);
            this.Controls.Add(this.loadBtn);
            this.Controls.Add(this.deleteBtn);
            this.Controls.Add(this.updateBtn);
            this.Controls.Add(this.newBtn);
            this.Controls.Add(this.levelLabel);
            this.Controls.Add(this.amountLabel);
            this.Controls.Add(this.mailingLabel);
            this.Controls.Add(this.idLabel);
            this.Controls.Add(this.phonenumLabel);
            this.Controls.Add(this.addressLabel);
            this.Controls.Add(this.nameLabel);
            this.Controls.Add(this.levelText);
            this.Controls.Add(this.amountText);
            this.Controls.Add(this.searchbyCbox);
            this.Controls.Add(this.searchText);
            this.Controls.Add(this.mailingCheckbox);
            this.Controls.Add(this.idText);
            this.Controls.Add(this.phonenumText);
            this.Controls.Add(this.addressText);
            this.Controls.Add(this.nameText);
            this.Controls.Add(this.customerListbox);
            this.Name = "RetailStore";
            this.Text = "Customer database";
            this.Load += new System.EventHandler(this.RetailStore_Load);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.ListBox customerListbox;
        private System.Windows.Forms.TextBox nameText;
        private System.Windows.Forms.TextBox addressText;
        private System.Windows.Forms.TextBox phonenumText;
        private System.Windows.Forms.TextBox idText;
        private System.Windows.Forms.CheckBox mailingCheckbox;
        private System.Windows.Forms.TextBox searchText;
        private System.Windows.Forms.ComboBox searchbyCbox;
        private System.Windows.Forms.TextBox amountText;
        private System.Windows.Forms.TextBox levelText;
        private System.Windows.Forms.Label nameLabel;
        private System.Windows.Forms.Label addressLabel;
        private System.Windows.Forms.Label phonenumLabel;
        private System.Windows.Forms.Label idLabel;
        private System.Windows.Forms.Label mailingLabel;
        private System.Windows.Forms.Label amountLabel;
        private System.Windows.Forms.Label levelLabel;
        private System.Windows.Forms.Button newBtn;
        private System.Windows.Forms.Button updateBtn;
        private System.Windows.Forms.Button deleteBtn;
        private System.Windows.Forms.Button loadBtn;
        private System.Windows.Forms.Label modeLabel;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Button calcBtn;
        private System.Windows.Forms.TextBox discText;
        private System.Windows.Forms.TextBox purchaseText;
    }
}

